apiVersion: v1
kind: DeploymentConfig
metadata:
  labels:
  app: microservice-app-example
  name: users-api
spec:
  replicas: 1
  selector:
  app: microservice-app-example
  deploymentconfig: users-api
  strategy:
  type: Rolling
  template:
  metadata:
    labels:
    app: microservice-app-example
    deploymentconfig: users-api
  spec:
    containers:
    -
    env:
    -
      name: JWT_SECRET
      value: myfancysecret
    -
      name: SERVER_PORT
      value: '8083'
    image: 172.30.1.1:5000/prod/users-api:latest
    command: ["java"]
    args: ["-jar", "-Dserver.port=8083", "/deployments/users-api-0.0.1-SNAPSHOT.jar"]
    name: users-api
    ports:
    -
      containerPort: 8083
    -
      containerPort: 8000
    imagePullPolicy: Always
    restartPolicy: Always
    resources:
      limits:
      memory: 1512Mi
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
    automatic: true
    containerNames:
      - users-api
    from:
      kind: ImageStreamTag
      name: users-api:latest
