apiVersion: v1
kind: Service
metadata:
  labels:
  app: microservice-app-example
  name: users-api
spec:
  ports:
  -
    name: web
    port: 8083
    protocol: TCP
  -
    port: 8000
    name: debug
    protocol: TCP
  selector:
  deploymentconfig: users-api
